FROM arm32v6/alpine:3.12@sha256:63d57a4b33f6150a184b36b9efd8acbdcd8b8f5fdf98fd75b49bc1ba7da8f3f8

LABEL maintainer="Thorsten Schifferdecker https://github.com/curx" \
  org.label-schema.vendor="Thorsten Schifferdecker" \
  org.label-schema.name="git" \      
  org.label-schema.version="1.1" \
  org.label-schema.schema-version="1.0"

ENTRYPOINT ["/usr/bin/git"]
CMD ["--help"]

RUN apk -U --no-cache add git

WORKDIR /data
